name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 3.0.0-dev
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cryptography: ^2.7.0
  hive: 
    path: ../hive
  path_provider: ^2.1.1
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
  mockito: ^5.4.5
  build_runner: ^2.4.15
